### ISSUE TITLE
error in logs Lite VIP" (v1.0.7)

### ISSUE THREAD

**Issue by Septembers** [partiusfabaa/cs2-LiteVIP#14]
[39;49m[37m21:46:43[39;49m[39;49m[30m [[39;49m[39;49m[37m[39;49m[37m[41mEROR[39;49m[39;49m[30m] (cssharp:[39;49m[39;49m[37mCore[39;49m[39;49m[30m) [39;49m[39;49m[37mError invoking callback[39;49m
[39;49m[37mSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.[39;49m
[39;49m[37m ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.[39;49m
[39;49m[37m   at LiteVip.LiteVip.Timer_Give(CCSPlayerController controller)[39;49m
[39;49m[37m   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)[39;49m
[39;49m[37m   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[39;49m
[39;49m[37m   --- End of inner exception stack trace ---[39;49m
[39;49m[37m   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[39;49m
[39;49m[37m   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)[39;49m
[39;49m[37m   at System.Delegate.DynamicInvokeImpl(Object[] args)[39;49m
[39;49m[37m   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82[39;49m
[39;49m[37m21:46:43[39;49m[39;49m[30m [[39;49m[39;49m[37m[39;49m[37m[41mEROR[39;49m[39;49m[30m] (cssharp:[39;49m[39;49m[37mCore[39;49m[39;49m[30m) [39;49m[39;49m[37mError invoking callback[39;49m
[39;49m[37mSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.[39;49m
[39;49m[37m ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.[39;49m
[39;49m[37m   at LiteVip.LiteVip.Timer_Give(CCSPlayerController controller)[39;49m
[39;49m[37m   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)[39;49m
[39;49m[37m   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[39;49m
[39;49m[37m   --- End of inner exception stack trace ---[39;49m
[39;49m[37m   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[39;49m
[39;49m[37m   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)[39;49m
[39;49m[37m   at System.Delegate.DynamicInvokeImpl(Object[] args)[39;49m
[39;49m[37m   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82[39;49m
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at CounterStrikeSharp.API.Modules.Utils.CHandle`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Index()
   at CounterStrikeSharp.API.Core.CEntityInstance.get_EntityIndex()
   at LiteVip.LiteVip.Timer_Give(CounterStrikeSharp.API.Core.CCSPlayerController)
   at DynamicClass.InvokeStub_Action.Invoke(System.Object, System.Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at CounterStrikeSharp.API.Core.FunctionReference+<>c__DisplayClass3_0.<.ctor>b__0(CounterStrikeSharp.API.Core.fxScriptContext*)

**Comment by Septembers** [comment]
Current API Version: 76

**Comment by ghostss2016** [comment]
09:34:19 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at LiteVip.LiteVip.OnTick(CCSPlayerController player) in G:\game_server\_cs2\LiteVIP\LiteVip\LiteVip.cs:line 527
   at LiteVip.LiteVip.<>c.<Load>b__11_5() in G:\game_server\_cs2\LiteVIP\LiteVip\LiteVip.cs:line 75
   at InvokeStub_OnTick.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass39_0`1.<RegisterListener>b__2(ScriptContext context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 318
   at InvokeStub_Action`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by mihaigsm2003** [comment]
18:04:16 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.WriteInt32(IntPtr ptr, Int32 ofs, Int32 val)
   at LiteVip.LiteVip.<>c__DisplayClass29_0.<Timer_Give>b__0()
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by partiusfabaa** [comment]
try [this](https://github.com/partiusfabaa/cs2-LiteVIP/releases/tag/v1.0.7.6)
