### ISSUE TITLE
After map change error

### ISSUE THREAD

**Issue by Prull99** [partiusfabaa/cs2-LiteVIP#19]
I use these plugins.
[Client]   List of all plugins currently loaded by CounterStrikeSharp: 19 plugins loaded.
[Client]   [#1:LOADED]: "AbNeR ShowDamage" (1.0.1) by AbNeR_CSS
[Client]     Shows damage dealt to enemies in the center text
[Client]   [#2:LOADED]: "K4-System" (v1.3.4) by K4ryuu
[Client]   [#3:LOADED]: "ColoredSmokeTeam" (v1.0.0)
[Client]   [#4:LOADED]: "DiscordServerInfo" (v1.0.0) by CYBERC4T
[Client]   [#5:LOADED]: "ResetScore" (v1.2.0) by CYBERC4T
[Client]   [#6:LOADED]: "HideLowerBody" (1.0.0) by DRANIX
[Client]     Allows players to hide their first person legs model. (lower body view model)
[Client]   [#7:LOADED]: "[Discord] ReportSystem by phantom" (v1.0.0)
[Client]   [#8:LOADED]: "Lite VIP" (v1.0.7) by thesamefabius
[Client]   [#9:LOADED]: "CustomCommands" (1.0.1) by HerrMagic
[Client]     Create your own commands per config
[Client]   [#10:LOADED]: "Connect Info" (v1.0.4) by gleb_khlebov
[Client]     Information about the player's location when connecting to chat and console
[Client]   [#11:LOADED]: "Admin List" (1.0) by Quake1011
[Client]   [#12:LOADED]: "AFK Manager" (0.0.8) by NiGHT & K4ryuu
[Client]   [#13:LOADED]: "DiscordLiveChat" (v1.0.1f) by CYBERC4T
[Client]   [#14:LOADED]: "CS2-Tags" (1.0.2) by daffyy
[Client]     Add player tags easily in cs2 game
[Client]   [#15:LOADED]: "AutoUpdater" (1.0.3) by DRANIX
[Client]     Auto Updater for Counter-Strike 2.
[Client]   [#16:LOADING]: "Advertisement" (v1.0.5) by thesamefabius
[Client]   [#17:LOADED]: "Round End Gravity" (0.0.1)
[Client]   [#18:LOADED]: "" ()
[Client]   [#19:LOADED]: "WeaponPaints" (1.3c) by Nereziel & daffyy
[Client]     Skin and knife selector, standalone and web-based

EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.WriteInt32(IntPtr ptr, Int32 ofs, Int32 val)
   at LiteVip.LiteVip.<>c__DisplayClass29_0.<Timer_Give>b__0()
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by partiusfabaa** [comment]
try [this](https://github.com/partiusfabaa/cs2-LiteVIP/releases/tag/v1.0.7.6)
