### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by daffyyyy** [partiusfabaa/cs2-LiteVIP#6]
Hi,
on csharp v30 errors appear in server console
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at LiteVip.LiteVip.OnTick(CCSPlayerController player) in /var/lib/pterodactyl/volumes/6ef877cd-d1a3-4412-8704-745b1ab7973a/game/csgo/addons/counterstrikesharp/source/LiteVip/LiteVip.cs:line 525
   at LiteVip.LiteVip.<>c.<Load>b__11_5() in /var/lib/pterodactyl/volumes/6ef877cd-d1a3-4412-8704-745b1ab7973a/game/csgo/addons/counterstrikesharp/source/LiteVip/LiteVip.cs:line 91
   at InvokeStub_OnTick.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass35_0`1.<RegisterListener>b__2(ScriptContext context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 295
   at InvokeStub_Action`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 81
```

**Comment by partiusfabaa** [comment]
[Recompiled for CSSharp V34](https://github.com/partiusfabaa/cs2-LiteVIP/releases/tag/v1.0.7.0)

**Comment by daffyyyy** [comment]
Same errors on line 524 with csharp v42 now :D

**Comment by mrdiega** [comment]
I confirm. Have no errors on v1.0.6.1fix
